// import icons
import 'bootstrap-icons/font/bootstrap-icons.css'

// import bootstrap
import 'bootstrap/dist/css/bootstrap.css'

import Script from "next/script";

import { Poppins } from "next/font/google";
import "./globals.css";
import Nav from "@/app/components/Nav";

const poppins = Poppins({
  subsets: ["latin"] ,
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100','200','300','400','500','600','700','800','900'],
});

export const metadata = {
  title: "Real Estate Agency Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={poppins.className}>
      <Nav />
      {children}
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossOrigin="anonymous"></Script>
    </body>
    </html>
  );
}
